### ISSUE TITLE
Use 'prop-types' package instead of React.PropTypes

### ISSUE THREAD

**Issue by MichaelDeBoey** [alexcurtis/react-treebeard#63]
`React.PropTypes` has been extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

CC: @alexcurtis

**Comment by uppe-r** [comment]
This error comes from [velocity-react](https://github.com/twitter-fabric/velocity-react). It is fixed in v.1.3.0 by [this pull request](https://github.com/twitter-fabric/velocity-react/pull/191)

**Comment by MichaelDeBoey** [comment]
@uppe-r `react-treebeard` uses also the deprecated `React.PropTypes`, like you can see in [`treebeard.js` L36-L46](https://github.com/alexcurtis/react-treebeard/blob/3046fc01edefb1b0806fa66d71ae5a761fdcf2b5/src/components/treebeard.js#L36-L46), [`header.js` L42-L49](https://github.com/alexcurtis/react-treebeard/blob/master/src/components/header.js#L42-L49), [`node.js` L100-L107](https://github.com/alexcurtis/react-treebeard/blob/master/src/components/node.js#L100-L107) & [`decorators.js` L97-L105](https://github.com/alexcurtis/react-treebeard/blob/master/src/components/decorators.js#L97-L105)

**Comment by uppe-r** [comment]
@MichaelDeBoey You're right, only looked at the first files in the Warning.

**Comment by MichaelDeBoey** [comment]
@uppe-r I'll try to look at it (again) tonight, but I thought that the tests were failing me and I couldn't seem to pass them so... 😕

**Comment by MichaelDeBoey** [comment]
@uppe-r Tried my best in #67, but still get some errors 😕
Maybe you can help?

**Comment by uppe-r** [comment]
@MichaelDeBoey I'm kinda new, but from what I managed to find, with [React v15](url) data-reactid is no longer used on every node (only server generated). As so, why is there still a check for reactid's on the tests?

**Comment by MichaelDeBoey** [comment]
@uppe-r That's strange 😕 Their test are still passing, but they shouldn't if it's no longer used since `React v15.0` ... 😕

**Comment by uppe-r** [comment]
@MichaelDeBoey The last PR's and non-PR's I see on Travis were using react@0.14, like https://travis-ci.org/alexcurtis/react-treebeard/builds/197948568#L849

**Comment by MichaelDeBoey** [comment]
Oh sh*t I thought the test were failing for some other reason... 😕

So I guess I can just delete the test using `reactid`...

**Comment by uppe-r** [comment]
Guess so @MichaelDeBoey . Doesn't make sense to keep something that isn't used anymore and just causes errors, right? 😆

**Comment by MichaelDeBoey** [comment]
Should be fixed now 🙂

@alexcurtis Can you look at #67 please?

**Comment by MichaelDeBoey** [comment]
@uppe-r Do you know a way to increase coverage again?
Don't see what caused the decrease 😕

**Comment by uppe-r** [comment]
@MichaelDeBoey No idea

**Comment by MichaelDeBoey** [comment]
`v2.0.0`is [released](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.0) as of now! 🙂
